##开发环境二

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  ## 邮件配置
  mail:
    host: smtp.163.com
    username: 19971481405@163.com
    password: ${MAIL_PASSWORD} #环境变量中获取秘钥
    port: 25
  data:
    ##Redis非关系形数据库配置
    redis:
      port: 6379
      host: 127.0.0.1
  servlet:
    # 配置servlet的multipart设置，用于文件上传
    multipart:
      # 启用multipart文件上传功能
      enabled: true
      # 设置单个文件的最大大小为10MBcdm
      max-file-size: 1000MB
      # 设置整个HTTP请求的最大大小为10MB，适应单文件或多文件上传
      max-request-size: 1000MB
server:
  port: 9090
mybatis:
  configuration:
    ##开启驼峰命名
    map-underscore-to-camel-case: true
  ##配置映射文件路径
  mapper-locations: mapper/*.xml
# 配置 MyBatis 控制台输出 SQL
logging:
  level:
    com.ligg.mapper: debug
# 七牛云配置
qiniu:
  access-key: ${QINIU_ACCESS_KEY}
  secret-key: ${QINIU_SECRET_KEY}
  bucket-name: videoplusligg
  domain: http://sowl9rtuo.hn-bkt.clouddn.com/ #域名
  video-path: videos/ # 新增的视频文件存储路径或前缀

bangumi:
  client-id: ${BANGUMI_CLIENT_ID}
  clinet-secret: ${BANGUMI_CLIENT_SECRET}
  redirect-uri: http://127.0.0.1:5501

